traj_file: "traj.csv"
save_video: True
Nsteps: 100
fps: 30
Npart: 2
shear_rate: 0    # artery [s^-1]
dt: 1.0e-10         # [s]

KT: 4.141947e-21      # [m^2 kg s^-2]
eta: 1.0e-3      # viscosity of water [Pa]
part_radius: 1.0e-9   # [m]