Npart: 10
shear_rate: 0.0     # [s^-1]
dt: 0.03
box_size_x: 50.0e-9       # [m]
box_size_y: 50.0e-9       # [m]

KT: 4.141947e-21      # [m^2 kg s^-2]
viscosity: 0.001      # water [Pa]
part_radius: 1.0e-9   # [m]