traj_file: "traj.csv"
save_video: False
Nsteps: 1000
fps: 1
Npart: 50
shear_rate:  1e7   # artery [s^-1]
dt: 2.0e-10         # [s]

enable_noise: False
KT: 4.1418e-21      # [m^2 kg s^-2]
eta: 1.0e-3      # viscosity of water [Pa]
part_radius: 1.0e-9   # [m]

test_mode: True  # applies upward force